spring:
  application:
    name: uaa-service
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security_demo_V1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: emreSskla2541
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
      oauth2:
        client:
          registration:
            google-idp:
              provider: google
              client-secret: ${GOOGLE_CLIENT_SECRET:{your_secret_key}}
              client-id: ${GOOGLE_CLIENT_ID:{your_client_id}}
              scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
              client-name: oauth2-client-web
          provider:
            google:
              user-name-attribute: email

server:
  port: 8080
logging:
  level:
    org:
      springframework:
        nodeValue: TRACE
        oauth2: TRACE
