spring:
  application:
    name: uaa-service

  security:
      oauth2:
        client:
          registration:
            google-idp:
              provider: google
              client-secret: ${GOOGLE_CLIENT_SECRET:{your_secret_key}}
              client-id: ${GOOGLE_CLIENT_ID:{your_client_id}}
              scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
              client-name: oauth2-client-web
          provider:
            google:
              user-name-attribute: email

server:
  port: 8080
logging:
  level:
    org:
      springframework:
        nodeValue: TRACE
        oauth2: TRACE

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: test
---
spring:
  config:
    activate:
      on-profile: prod
