spring:
  config:
    import: secrets.yml

  application:
    name: uaa-service


server:
  port: 8080
logging:
  level:
    org:
      springframework:
        nodeValue: TRACE
        oauth2: TRACE

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: test
---
spring:
  config:
    activate:
      on-profile: prod
